name: Build and Package on Release

on:
  push:
    tags:
      - "v*" # Trigger on tags that start with 'v', e.g., 'v1.0', 'v2.1.3'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "pyinstaller>=5.0,<6.0"

      - name: Build with PyInstaller
        run: pyinstaller --clean --noconfirm --windowed --onefile .\pomodoro.py --add-data "alarm.wav;."

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: pomodoro.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for tag ${{ github.ref_name }}"
          allowUpdates: true
